services:
  web:
    image: hris/hris-web:latest
    container_name: hris-web
    ports:
      - "3000:80"
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - hris_net
    environment:
      - VITE_API_BACKEND_URL=/api

  api:
    image: nginx:alpine
    container_name: hris-api
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ../hris-api:/var/www/html
    depends_on:
      - api-fpm
    networks:
      - hris_net
    ports:
      - "8000:80"

  api-fpm:
    image: hris/hris-api:latest
    container_name: hris-api-fpm
    env_file:
      - .env.prod
    volumes:
      - ../hris-api:/var/www/html
    networks:
      - hris_net

  db:
    image: postgres:16
    container_name: hris-db
    environment:
      POSTGRES_DB: hris
      POSTGRES_USER: hris
      POSTGRES_PASSWORD: secret
    volumes:
      - hris_pg:/var/lib/postgresql/data
    networks:
      - hris_net

networks:
  hris_net:
    driver: bridge

volumes:
  hris_pg: